# Generated by Django 3.1.4 on 2020-12-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llexchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSFW_Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsfw_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='is_Tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llexchange.user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tutor_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='llexchange.user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llexchange.user'),
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
