# Generated by Django 3.1.4 on 2020-12-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llexchange', '0002_auto_20201224_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Tutor',
            new_name='is_staff',
        ),
        migrations.AlterField(
            model_name='moderator',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
