# Generated by Django 3.1.4 on 2021-01-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llexchange', '0003_auto_20201224_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NSFW_Words',
        ),
        migrations.RemoveField(
            model_name='language',
            name='creator',
        ),
        migrations.AddField(
            model_name='language',
            name='moderators',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='llexchange.moderator'),
        ),
        migrations.AddField(
            model_name='language',
            name='tutors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='llexchange.user'),
        ),
        migrations.AlterField(
            model_name='language',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='llexchange.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='flag',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='llexchange.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
