# Generated by Django 3.1.4 on 2021-01-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llexchange', '0004_auto_20210103_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='llexchange.user')),
                ('userb', models.ManyToManyField(related_name='blocked_by', to='llexchange.User')),
            ],
        ),
    ]
